# Validation - All the scoring we've done so far is wrong

# Machine Learning only cares how well you do on unseen data

### First idea, hold out some data for training

NOTE, because the Decision Tree Model had a 95% accuracy does not mean it's accurate because it's created using the data and evaluated against same data.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.options.display.max_columns = 100
%matplotlib inline

heart = pd.read_csv('data/heart.csv')
heart.head()

slope               thal  rest_bp  chest_pain  num_major_vessels  sugar  \
0      1             normal      128           2                  0      0   
1      2             normal      110           3                  0      0   
2      1             normal      125           4                  3      0   
3      1  reversible_defect      152           4                  0      0   
4      3  reversible_defect      178           1                  0      0   

   rest_ekg  chol  oldpeak     sex  age  max_heart_rate  angina  disease  
0         2   308      0.0    male   45             170       0        0  
1         0   214      1.6  female   54             158       0        0  
2         2   304      0.0    male   77             162       1        1  
3         0   223      0.0    male   40             181       0        1  
4         2   270      4.2    male   59             145       0        0

In [2]:
X = heart[['max_heart_rate', 'rest_bp']].values
y = heart['disease'].values

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=123)

In [5]:
X_train.shape

(135, 2)

In [6]:
y_train.shape

(135,)

In [7]:
X_test.shape

(45, 2)

In [8]:
y_test.shape

(45,)

### Once data is split into train and test, learn on the training set and evaluate on the test set

In [10]:
from sklearn.tree import DecisionTreeClassifier
dtr = DecisionTreeClassifier()

In [11]:
dtr.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [12]:
dtr.score(X_test, y_test)
# Note that the pct < random guesses aka baseline

0.53333333333333333

### Let's see how our Decision Tree did when evaluating it on the same data that it was trained on
Training score is much higher than test score!

In [13]:
dtr.score(X_train, y_train)

0.99259259259259258

# Cross Validation

![][1]

The **`cross_val_score`** function automates the process of doing cross validation. Simply pass it an estimator, the data, and the number of validation sets to use. The estimator does NOT need to be trained. **`cross_val_score`** will handle that for you.

[1]: images/kf.png

In [14]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

In [17]:
rfc2 =RandomForestClassifier()

In [18]:
cross_val_score(rfc2,X, y, cv=5)

array([ 0.52777778,  0.52777778,  0.58333333,  0.44444444,  0.55555556])

In [19]:
scores = cross_val_score(rfc2,X, y, cv=5)
scores.mean()

0.58333333333333326

## Assignment
Use **`cross_val_score`** to see how other machine learning models are likely to fair when used on unseen data.

In [20]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

In [21]:
knn2 = KNeighborsClassifier()

In [23]:
cross_val_score(knn2,X, y, cv=5)

array([ 0.61111111,  0.61111111,  0.58333333,  0.58333333,  0.61111111])

In [24]:
svmscores = cross_val_score(knn2,X, y, cv=5)
svmscores.mean()

0.60000000000000009

In [26]:
from sklearn.model_selection import cross_val_score
from sklearn.gaussian_process import GaussianProcessClassifier

In [27]:
gpc = GaussianProcessClassifier()

In [28]:
cross_val_score(gpc,X, y, cv=5)

array([ 0.5       ,  0.41666667,  0.5       ,  0.41666667,  0.61111111])

In [29]:
gpcscores = cross_val_score(gpc,X, y, cv=5)
gpcscores.mean()

0.48888888888888893

In [30]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import SGDClassifier

In [31]:
sgdc =SGDClassifier()

In [34]:
cross_val_score(sgdc,X, y, cv=5)

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/anaconda3/lib/python3.6/site-packages/s

array([ 0.55555556,  0.55555556,  0.55555556,  0.58333333,  0.66666667])

In [36]:
sgdcscores = cross_val_score(sgdc,X, y, cv=5)
sgdcscores.mean()

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/anaconda3/lib/python3.6/site-packages/s

0.57777777777777772

# Use KFold specifically from scikit-learn
This will shuffle the data. cross_val_score doesn't do this.

In [1]:
from sklearn.model_selection import KFold

In [2]:
kf = KFold(n_splits=5, shuffle=True)

In [6]:
from sklearn.model_selection import cross_val_score

In [11]:
cross_val_score(sgdc, X, y, cv=loo)

NameError: name 'sgdc' is not defined